# OBet — development commands
# Usage: just <recipe>

# ── Infrastructure ────────────────────────────────────────────────────────────

# Start all services (detached)
up:
    docker compose up -d

# Start all services and rebuild images
up-build:
    docker compose up -d --build

# Stop all services
down:
    docker compose down

# Stop all services and wipe volumes (full reset)
down-v:
    docker compose down -v

# Rebuild all Docker images
build:
    docker compose build

# Follow logs for all services (or pass a service name)
logs *SERVICE:
    docker compose logs -f {{SERVICE}}

# Show status of all services
ps:
    docker compose ps

# ── Database ──────────────────────────────────────────────────────────────────

# Run all pending migrations
migrate:
    docker compose exec backend uv run alembic upgrade head

# Roll back last migration
rollback:
    docker compose exec backend uv run alembic downgrade -1

# Create a new autogenerated migration
# Usage: just makemigration "add_something"
makemigration NAME:
    docker compose exec backend uv run alembic revision --autogenerate -m "{{NAME}}"

# Open an interactive psql shell in the database container
db-shell:
    docker compose exec db psql -U obet -d obet

# ── Backend ───────────────────────────────────────────────────────────────────

# Start backend dev server locally (hot reload, no Docker)
backend-dev:
    cd backend && uv run uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload

# Open a bash shell inside the running backend container
backend-shell:
    docker compose exec backend bash

# View only backend logs
backend-logs:
    docker compose logs -f backend

# ── Frontend ──────────────────────────────────────────────────────────────────

# Start frontend dev server locally (hot reload, no Docker)
frontend-dev:
    cd frontend && pnpm dev

# Run TypeScript type check
typecheck:
    cd frontend && pnpm exec tsc --noEmit

# Run ESLint
lint:
    cd frontend && pnpm lint

# Open a shell inside the running frontend container
frontend-shell:
    docker compose exec frontend sh

# View only frontend logs
frontend-logs:
    docker compose logs -f frontend

# ── Setup ─────────────────────────────────────────────────────────────────────

# Copy example env files (run once after cloning)
init:
    @cp -n backend/example.env backend/.env && echo "Created backend/.env" || echo "backend/.env already exists"
    @echo "Done — edit backend/.env before starting services"

# Full fresh start: build, start, migrate
bootstrap: init up-build
    @echo "Waiting for services to be healthy..."
    @sleep 5
    just migrate
    @echo ""
    @echo "OBet is running:"
    @echo "  Frontend  → http://localhost:3000"
    @echo "  Backend   → http://localhost:8000"
    @echo "  API docs  → http://localhost:8000/docs"
